-- COMPLETE SCHEMA MIGRATION
-- Execute this in the Supabase SQL Editor

-- 1. Helper Functions
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
    AND role = 'ADMIN'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. Base Tables (No internal FK dependencies)

-- PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  full_name text,
  email text,
  role text DEFAULT 'OPERATOR'::text,
  status text DEFAULT 'ACTIVE'::text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  whatsapp text,
  recovery_code text,
  recovery_expiry timestamp with time zone,
  stripe_customer_id text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-- PLANS
CREATE TABLE IF NOT EXISTS public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  max_instances integer DEFAULT 1,
  max_contacts integer DEFAULT 100,
  max_chatbots integer DEFAULT 1,
  features jsonb DEFAULT '[]'::jsonb,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  cycle text DEFAULT 'monthly'::text,
  stripe_price_id text,
  mercado_pago_id text,
  status text DEFAULT 'ACTIVE'::text,
  max_users integer DEFAULT 1,
  ai_enabled boolean DEFAULT false,
  stripe_product_id text,
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);

-- SYSTEM SETTINGS
CREATE TABLE IF NOT EXISTS public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  api_url text,
  api_key text,
  webhook_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  system_instance text,
  test_phone text,
  captcha_provider text DEFAULT 'none'::text,
  captcha_site_key text,
  captcha_secret_key text,
  maintenance_mode boolean DEFAULT false,
  maintenance_return_time timestamp with time zone,
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);

-- ADMIN SETTINGS
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value text,
  description text,
  category text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_settings_pkey PRIMARY KEY (id)
);

-- EMAIL TEMPLATES
CREATE TABLE IF NOT EXISTS public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  subject text NOT NULL,
  body text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);

-- DEBUG LOGS
CREATE TABLE IF NOT EXISTS public.debug_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),
  content text
);


-- 3. Dependent Tables (Level 1)

-- SUBSCRIPTIONS (Depends on Plans + Auth)
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  plan_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  current_period_start timestamp with time zone DEFAULT now(),
  stripe_subscription_id text,
  cancel_at_period_end boolean DEFAULT false,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);

-- INSTANCES (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  status text DEFAULT 'DISCONNECTED'::text,
  battery integer,
  identifier text NOT NULL UNIQUE,
  type text DEFAULT 'whatsapp'::text,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  sector text DEFAULT 'Comercial'::text,
  owner_jid text,
  CONSTRAINT instances_pkey PRIMARY KEY (id),
  CONSTRAINT instances_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- INTEGRATIONS (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  credentials jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integrations_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- AI SETTINGS (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.ai_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  api_key text,
  model text DEFAULT 'gemini-1.5-flash'::text,
  system_prompt text DEFAULT 'Você é um assistente prestativo da Evolution API.'::text,
  enabled boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  temperature double precision DEFAULT 0.7,
  max_tokens integer DEFAULT 800,
  history_limit integer DEFAULT 5,
  provider text DEFAULT 'gemini'::text CHECK (provider = ANY (ARRAY['gemini'::text, 'chatgpt'::text])),
  CONSTRAINT ai_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ai_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- API KEYS (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  key text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- BUSINESS HOURS (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.business_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  enabled boolean DEFAULT false,
  away_message text NOT NULL DEFAULT 'Olá! No momento estamos fora do horário de atendimento. Retornaremos em breve.'::text,
  monday_enabled boolean DEFAULT true,
  monday_start time without time zone DEFAULT '08:00:00'::time without time zone,
  monday_end time without time zone DEFAULT '18:00:00'::time without time zone,
  tuesday_enabled boolean DEFAULT true,
  tuesday_start time without time zone DEFAULT '08:00:00'::time without time zone,
  tuesday_end time without time zone DEFAULT '18:00:00'::time without time zone,
  wednesday_enabled boolean DEFAULT true,
  wednesday_start time without time zone DEFAULT '08:00:00'::time without time zone,
  wednesday_end time without time zone DEFAULT '18:00:00'::time without time zone,
  thursday_enabled boolean DEFAULT true,
  thursday_start time without time zone DEFAULT '08:00:00'::time without time zone,
  thursday_end time without time zone DEFAULT '18:00:00'::time without time zone,
  friday_enabled boolean DEFAULT true,
  friday_start time without time zone DEFAULT '08:00:00'::time without time zone,
  friday_end time without time zone DEFAULT '18:00:00'::time without time zone,
  saturday_enabled boolean DEFAULT false,
  saturday_start time without time zone DEFAULT '09:00:00'::time without time zone,
  saturday_end time without time zone DEFAULT '13:00:00'::time without time zone,
  sunday_enabled boolean DEFAULT false,
  sunday_start time without time zone DEFAULT '09:00:00'::time without time zone,
  sunday_end time without time zone DEFAULT '13:00:00'::time without time zone,
  timezone text DEFAULT 'America/Sao_Paulo'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_hours_pkey PRIMARY KEY (id),
  CONSTRAINT business_hours_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- CONTACTS (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  remote_jid text NOT NULL UNIQUE,
  avatar_url text,
  email text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  tags text[] DEFAULT '{}'::text[],
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- AWAY MESSAGES SENT (Depends on Auth)
CREATE TABLE IF NOT EXISTS public.away_messages_sent (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  remote_jid text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT away_messages_sent_pkey PRIMARY KEY (id),
  CONSTRAINT away_messages_sent_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- PAYMENT LOGS (Depends on Profiles/Auth)
CREATE TABLE IF NOT EXISTS public.payment_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'BRL'::text,
  method text,
  status text,
  external_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_logs_pkey PRIMARY KEY (id),
  CONSTRAINT payment_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);


-- 4. Dependent Tables (Level 2)

-- FLOWS (Depends on Auth, Instances)
CREATE TABLE IF NOT EXISTS public.flows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  nodes jsonb NOT NULL DEFAULT '[]'::jsonb,
  edges jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text DEFAULT 'DRAFT'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'ACTIVE'::text, 'PAUSED'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  instance_id uuid,
  trigger_type text DEFAULT 'any'::text,
  trigger_keyword text,
  CONSTRAINT flows_pkey PRIMARY KEY (id),
  CONSTRAINT flows_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT flows_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id)
);

-- CHATBOTS (Depends on Auth, Instances)
CREATE TABLE IF NOT EXISTS public.chatbots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  trigger text,
  instance_id uuid,
  status text DEFAULT 'ACTIVE'::text,
  last_run timestamp with time zone,
  type text DEFAULT 'SIMPLE'::text,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  match_type text DEFAULT 'contains'::text CHECK (match_type = ANY (ARRAY['exact'::text, 'contains'::text, 'starts'::text, 'ends'::text])),
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chatbots_pkey PRIMARY KEY (id),
  CONSTRAINT chatbots_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id),
  CONSTRAINT chatbots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- 5. Dependent Tables (Level 3)

-- CHATBOT STEPS (Depends on Chatbots)
CREATE TABLE IF NOT EXISTS public.chatbot_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chatbot_id uuid,
  type text NOT NULL,
  content text NOT NULL,
  delay integer DEFAULT 2,
  simulate_typing boolean DEFAULT true,
  "order" integer NOT NULL, -- Fixed reserved word quoting
  created_at timestamp with time zone DEFAULT now(),
  next_step_id uuid,
  CONSTRAINT chatbot_steps_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_steps_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES public.chatbots(id),
  CONSTRAINT chatbot_steps_next_step_id_fkey FOREIGN KEY (next_step_id) REFERENCES public.chatbot_steps(id)
);

-- CONVERSATIONS (Depends on Instances, Auth, Flows, Profiles)
CREATE TABLE IF NOT EXISTS public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_name text NOT NULL,
  contact_avatar text,
  last_message text,
  last_message_time timestamp with time zone,
  unread_count integer DEFAULT 0,
  online boolean DEFAULT false,
  instance_id uuid,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  remote_jid text,
  status text DEFAULT 'pending'::text,
  is_blocked boolean DEFAULT false,
  last_greeted_at timestamp with time zone,
  last_flow_at timestamp with time zone,
  current_flow_id uuid,
  current_node_id text,
  variables jsonb DEFAULT '{}'::jsonb,
  assigned_agent_id uuid,
  assigned_at timestamp with time zone,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.instances(id),
  CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_current_flow_id_fkey FOREIGN KEY (current_flow_id) REFERENCES public.flows(id),
  CONSTRAINT conversations_assigned_agent_id_fkey FOREIGN KEY (assigned_agent_id) REFERENCES public.profiles(id)
);


-- 6. Dependent Tables (Level 4)

-- MESSAGES (Depends on Conversations)
CREATE TABLE IF NOT EXISTS public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  text text NOT NULL,
  sender text NOT NULL,
  status text DEFAULT 'sent'::text,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  media_url text,
  media_type text,
  mimetype text,
  filename text,
  wamid text,
  quoted_id uuid,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_quoted_id_fkey FOREIGN KEY (quoted_id) REFERENCES public.messages(id)
);


-- 7. Enable RLS (Batch)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.away_messages_sent ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chatbots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chatbot_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 8. Basic Policies (Generic Safe Defaults - You may need to refine these based on your earlier inputs)
-- (Excluded for brevity as the user already has them or can add them, focusing on schema creation first to fix errors)
-- But ensuring is_admin based policies exist:

CREATE POLICY "Admins manage all logs" ON public.payment_logs FOR ALL USING (is_admin()) WITH CHECK (is_admin());

-- Re-insert default templates if needed
INSERT INTO email_templates (slug, subject, body) VALUES 
('plan_expiry', 'Aviso de Vencimento', 'Olá {{full_name}}! Sua assinatura do Evolution Leve expira em breve ({{expiry_date}}). Não deixe para a última hora, renove agora!'),
('payment_reminder', 'Lembrete de Pagamento', 'Olá {{full_name}}! Identificamos um pagamento pendente em sua conta. Clique aqui para regularizar: {{payment_link}}'),
('welcome', 'Boas-vindas', 'Bem-vindo ao Evolution Leve, {{full_name}}! Sua conta foi criada com sucesso. Acesse o painel aqui: {{app_url}}'),
('password_reset', 'Recuperação de Acesso', 'Olá! Você solicitou a recuperação de senha. Use este link para redefinir: {{reset_link}}'),
('subscription_confirmed', 'Confirmação de Assinatura', 'Tudo pronto, {{full_name}}! Sua assinatura foi confirmada e seus limites foram atualizados. Aproveite!')
ON CONFLICT (slug) DO NOTHING;

-- 9. RLS Policies (Critical for Frontend Access)

-- Allow users to view/edit their own profile
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Allow public access to system settings (needed for Login/Register page to get Captcha key)
DROP POLICY IF EXISTS "Public view system settings" ON public.system_settings;
CREATE POLICY "Public view system settings" ON public.system_settings FOR SELECT USING (true);

-- 10. Auto-Profile Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'User'), 
    new.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 11. Seed System Settings (Evolution API)
INSERT INTO public.system_settings (id, api_url, api_key, created_at, updated_at, captcha_provider)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'https://api.ublochat.com.br',
  'f534ab200345bc2b35ef679dde6e61ec',
  NOW(),
  NOW(),
  'none'
)
ON CONFLICT (id) DO UPDATE SET
  api_url = EXCLUDED.api_url,
  api_key = EXCLUDED.api_key;

